site_name: Django Glue
site_url: https://django-glue.stratusadv.com

repo_name: stratusadv/django-glue
repo_url: https://github.com/stratusadv/django-glue

copyright: Copyright (c) 2024 Stratus Advanced Technologies and Contributors

extra_css:
  - static/css/extra.css
  - static/css/mkdocstrings.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - static/js/extra.js


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
  - tables
  - attr_list


nav:
  - Getting Started:
      - Welcome: index.md
      - Installation: getting_started/installation.md
  - API Reference:
      - Glue:
          - shortcuts: api/glue/shortcuts.md
          - FunctionGlue: api/glue/function_glue.md
          - ModelObjectGlue: api/glue/model_object_glue.md
          - QuerySetGlue: api/glue/query_set_glue.md
          - TemplateGlue: api/glue/template_glue.md
      - Javascript:
          - FunctionGlue: api/javascript/function_glue.md
          - ModelObjectGlue: api/javascript/model_object_glue.md
          - QuerySetGlue: api/javascript/query_set_glue.md
          - TemplateGlue: api/javascript/template_glue.md
          - ViewGlue: api/javascript/view_glue.md
  - Changelog:
      - Current: changelog/changelog.md
      - Archived: changelog/archived_changelog.md
  - Roadmap:
      - Current: roadmap/roadmap.md
  - About:
      - Contributors: about/contributors.md

plugins:
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
          options:
            show_source: true
            show_if_no_docstring: True
            docstring_style: sphinx
            docstring_section_style: list
            members_order: source
            merge_init_into_class: true
            show_root_full_path: true
            show_root_heading: true
            show_signature: false
            show_signature_annotations: false
            show_symbol_type_heading: true
  - markdown-exec
  - search
  - table-reader

theme:
  name: material
  custom_dir: docs/templates
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/lightbulb
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to system preference"
  features:
    - toc.follow
    - navigation.tabs
    - navigation.footer
    - navigation.sections
  logo: 'static/img/django_glue_logo_white_256.png'
  favicon: 'favicon.png'

watch:
  - django_glue
  - example
  - test_example
  - tests
