# Generated by Django 4.0.4 on 2022-05-20 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGlue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(editable=False)),
                ('key', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('method', models.CharField(choices=[('rea', 'Read'), ('rea', 'Write'), ('del', 'Delete')], default='rea', editable=False, max_length=3)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expiry_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldGlue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(editable=False)),
                ('key', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('method', models.CharField(choices=[('rea', 'Read'), ('rea', 'Write'), ('del', 'Delete')], default='rea', editable=False, max_length=3)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expiry_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('field_name', models.CharField(editable=False, max_length=64)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='objectglue',
            index=models.Index(fields=['key', 'content_type', 'object_id'], name='django_glue_key_c1f051_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldglue',
            index=models.Index(fields=['key', 'content_type', 'object_id'], name='django_glue_key_d12459_idx'),
        ),
    ]
