# Generated by Django 5.2.4 on 2025-08-09 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gorilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('age', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('fight_style', models.CharField(choices=[('box', 'Boxing'), ('mua', 'Muay Thai'), ('bjj', 'Brazilian Jiu Jitsu'), ('wre', 'Wrestling'), ('kar', 'Karate'), ('tae', 'Taekwondo'), ('jud', 'Judo'), ('kic', 'Kickboxing'), ('mix', 'Mixed Style'), ('bra', 'Brawler')], default='bra', max_length=20)),
                ('rank_points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gorilla',
                'verbose_name_plural': 'Gorillas',
                'db_table': 'gorilla',
            },
        ),
    ]
