__VERSION__ = '1.0.0'

UNIQUE_NAME_KEY = 'unique_name'
ACTION_KEY = 'action'
GLUE_TYPE_KEY = 'glue_type'

# Fields
ALL_DUNDER_KEY = '__all__'
NONE_DUNDER_KEY = '__none__'

# Context
DJANGO_GLUE_VERSION = 'DJANGO_GLUE_VERSION'
KEEP_LIVE_INTERVAL_TIME_MILLISECONDS_CONTEXT_NAME = 'DJANGO_GLUE_KEEP_LIVE_INTERVAL_TIME_MILLISECONDS'
DJANGO_GLUE_SESSION_DATA = 'DJANGO_GLUE_SESSION_DATA'
DJANGO_GLUE_URLS = 'DJANGO_GLUE_URLS'
DJANGO_GLUE_URL_APP_NAME = 'DJANGO_GLUE_URL_APP_NAME'

# Url
BASE_URL_NAME = 'django_glue'
ACTION_URL_NAME = 'action'
KEEP_LIVE_HANDLER_URL_NAME = 'keep_live'
SESSION_DATA_URL_NAME = 'session_data'
