__VERSION__ = '1.0.0a5'

UNIQUE_NAME_KEY = 'unique_name'
BOUND_ATTRIBUTE_KEY = 'bound_attribute'
GLUE_TYPE_KEY = 'glue_type'

# Fields
ALL_DUNDER_KEY = '__all__'
NONE_DUNDER_KEY = '__none__'

# Context
DJANGO_GLUE_VERSION_KEY = 'DJANGO_GLUE_VERSION'
DJANGO_GLUE_SESSION_PROXY_REGISTRY_KEY = 'DJANGO_GLUE_SESSION_PROXY_REGISTRY'
DJANGO_GLUE_URLS_KEY = 'DJANGO_GLUE_URLS'
DJANGO_GLUE_PROXIES_KEY = 'DJANGO_GLUE_PROXIES'
DJANGO_GLUE_PROXIES_REQUEST_ATTR_KEY = '__glue_proxies__'
DJANGO_GLUE_PROXIES_SCRIPT_NAME_KEY = 'DJANGO_GLUE_PROXIES_SCRIPT_NAME'
DJANGO_GLUE_PROXIES_SCRIPT_NAME = 'django-glue-proxies'

# Url
BASE_URL_NAME = '__dg__'
BOUND_ATTRIBUTE_EVENT_URL_NAME = 'bound_attribute_event'
GLUE_VIEW_URL_NAME = 'glue_view'
