__VERSION__ = '1.0.0a2'

UNIQUE_NAME_KEY = 'unique_name'
ACTION_KEY = 'action'
GLUE_TYPE_KEY = 'glue_type'

# Fields
ALL_DUNDER_KEY = '__all__'
NONE_DUNDER_KEY = '__none__'

# Context
DJANGO_GLUE_VERSION_KEY = 'DJANGO_GLUE_VERSION'
DJANGO_GLUE_KEEP_LIVE_INTERVAL_TIME_SECONDS_KEY = 'DJANGO_GLUE_KEEP_LIVE_INTERVAL_TIME_MILLISECONDS'
DJANGO_SESSION_EXPIRY_MESSAGE_KEY = 'DJANGO_SESSION_EXPIRY_MESSAGE'
DJANGO_GLUE_SESSION_PROXY_REGISTRY_KEY = 'DJANGO_GLUE_SESSION_PROXY_REGISTRY'
DJANGO_GLUE_URLS_KEY = 'DJANGO_GLUE_URLS'
DJANGO_GLUE_PROXIES_CONTEXT_DATA_KEY = 'DJANGO_GLUE_PROXIES_CONTEXT_DATA'

# Url
BASE_URL_NAME = '__dg__'
ACTION_URL_NAME = 'action'
KEEP_LIVE_URL_NAME = 'keep_live'
SESSION_DATA_URL_NAME = 'session_data'
GLUE_VIEW_URL_NAME = 'glue_view'
