DJANGO_GLUE_SESSION_PROXY_KEY = 'django_glue_proxies'

DJANGO_GLUE_PROXY_POLICY_MAX_AGE_SECONDS = 86400 # 24 Hours

DJANGO_GLUE_VIEW_MAX_REDIRECTS = 10

DJANGO_GLUE_REQUEST_TIMEOUT_SECONDS = 30

DJANGO_GLUE_QUERYSET_BATCH_SIZE = 100
