name: 'Security Scan'
description: 'An action to perform a security audit to identify vulnerabilities, secrets, and dependency issues.'

inputs:
  python-version:
    description: 'Python version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Setup Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install project dependencies
      run: uv sync
      shell: bash

    - name: Install security tools
      run: uv tool install pip-audit
      shell: bash

    - name: Run pip-audit
      run: uv tool run pip-audit | tee pip_audit_report.txt
      shell: bash

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
        sudo mv ./bin/trivy /usr/local/bin/trivy
      shell: bash

    - name: Run Trivy
      run: trivy fs . --severity LOW,MEDIUM,HIGH,CRITICAL --format table | tee trivy_report.txt
      shell: bash

    - name: Install TruffleHog 3
      run: |
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh \
        | sudo sh -s -- -b /usr/local/bin
      shell: bash

    - name: Run TruffleHog
      run: trufflehog filesystem . --json --no-update | tee trufflehog_report.txt
      shell: bash

    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          pip_audit_report.txt
          trivy_report.txt
          trufflehog_report.txt
        retention-days: 7
