# Generated by Django 5.2.6 on 2026-08-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('species', models.CharField(choices=[('Coleoptera', 'Coleoptera'), ('Diptera', 'Diptera'), ('Hemiptera', 'Hemiptera'), ('Hymenoptera', 'Hymenoptera'), ('Lepidoptera', 'Lepidoptera'), ('Odonata', 'Odonata'), ('Orthoptera', 'Orthoptera')], max_length=32)),
                ('weight', models.FloatField(help_text='Weight in milligrams')),
                ('catalogue_number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'lab_specimen',
                'ordering': ['catalogue_number'],
            },
        ),
    ]
