# Generated by Django 5.2.7 on 2026-03-03 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gorilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('weight', models.FloatField(default=200.0, help_text='Weight in kg', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('height', models.FloatField(default=1.8, help_text='Height in meters', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.5)])),
                ('fight_style', models.CharField(choices=[('box', 'Boxing'), ('mua', 'Muay Thai'), ('bjj', 'Brazilian Jiu-Jitsu'), ('wre', 'Wrestling'), ('kar', 'Karate'), ('tae', 'Taekwondo'), ('jud', 'Judo'), ('kic', 'Kickboxing'), ('mix', 'Mixed Style'), ('bra', 'Brawler')], default='bra', max_length=20)),
                ('rank_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
    ]
