# Generated by Django 6.0.6 on 2026-07-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorilla',
            name='fighting_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Fighting statistics: wins, losses, knockouts, favorite_moves, etc.'),
        ),
    ]
