# Generated by Django 5.2.7 on 2026-03-11 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'gorilla_skill',
            },
        ),
        migrations.RemoveField(
            model_name='gorilla',
            name='fight_style',
        ),
        migrations.AddField(
            model_name='gorilla',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Fighter profile photo', null=True, upload_to='gorilla_photos/'),
        ),
        migrations.AlterModelTable(
            name='gorilla',
            table='gorilla',
        ),
        migrations.AddField(
            model_name='gorilla',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='gorillas', to='gorilla.skill'),
        ),
    ]
