# Generated by Django 6.0.6 on 2026-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0002_gorilla_fighting_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorilla',
            name='signature',
            field=models.BinaryField(blank=True, help_text='Unique battle signature (binary data)', null=True),
        ),
    ]
