# Generated by Django 5.2.4 on 2025-08-09 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability', '0001_initial'),
        ('gorilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorillaCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('level', models.IntegerField(choices=[(1, 'Novice'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert'), (6, 'Master')], default=3)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorilla_capabilities', related_query_name='gorilla_capability', to='capability.capability')),
                ('gorilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', related_query_name='capability', to='gorilla.gorilla')),
            ],
            options={
                'verbose_name': 'Gorilla Capability',
                'verbose_name_plural': 'Gorilla Capabilities',
                'db_table': 'gorilla_capability',
            },
        ),
    ]
