# Generated by Django 5.2.7 on 2026-03-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gorilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('location', models.CharField(choices=[('thu', 'Thunderdome'), ('col', 'Colosseum'), ('aml', 'Abandoned Mall'), ('nin', 'Ninja Dojo'), ('din', 'Dinosaur Island'), ('vol', 'Volcano Crater'), ('pir', 'Pirate Cove'), ('ali', 'Alien Wasteland')], default='din', max_length=3)),
                ('weather_conditions', models.CharField(choices=[('pbs', 'Perfect Blue Sky'), ('omc', 'Ominous Clouds'), ('tor', 'Torrential Downpour'), ('apt', 'Apocalyptic Thunder'), ('blz', 'Blizzard Fury'), ('scr', 'Scorching Inferno'), ('arc', 'Arctic Freeze'), ('hur', 'Hurricane Force'), ('mst', 'Mysterious Mist')], default='pbs', max_length=3)),
                ('spectator_count', models.IntegerField(default=0)),
                ('terrain_type', models.CharField(choices=[('sdc', 'Steel Death Cage'), ('frd', 'Flaming Ring of Doom'), ('btf', 'Bouncy Trampoline Floor'), ('egf', 'Electric Grass Field'), ('qst', 'Quicksand Trap'), ('cpp', 'Chocolate Pudding Pit'), ('lva', 'Lava Floor'), ('sbf', 'Spiky Boulder Field'), ('siw', 'Shark Infested Waters')], default='sdc', max_length=3)),
                ('status', models.CharField(choices=[('sch', 'Scheduled'), ('inp', 'In Progress'), ('cmp', 'Completed'), ('cnc', 'Cancelled'), ('pst', 'Postponed'), ('drw', 'Draw'), ('nct', 'No Contest')], default='sch', max_length=3)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('blue_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_blue_corner', to='gorilla.gorilla')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_lost', to='gorilla.gorilla')),
                ('red_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_red_corner', to='gorilla.gorilla')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_won', to='gorilla.gorilla')),
            ],
            options={
                'verbose_name': 'Fight',
                'verbose_name_plural': 'Fights',
                'db_table': 'fight',
            },
        ),
    ]
