# Generated by Django 6.0.6 on 2026-07-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='status',
            field=models.CharField(choices=[('sch', 'Scheduled'), ('inp', 'In Progress'), ('cmp', 'Completed'), ('cnc', 'Cancelled'), ('pst', 'Postponed'), ('drw', 'Draw'), ('nct', 'No Contest')], default='sch', max_length=3, null=True),
        ),
    ]
