# Generated by Django 5.2.4 on 2025-08-09 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('phy', 'Physical Attribute'), ('ski', 'Striking Skill'), ('gra', 'Grappling Skill'), ('def', 'Defensive Skill'), ('spe', 'Special Technique'), ('fig', 'Fight Style')], default='phy', max_length=3)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'db_table': 'capability',
            },
        ),
    ]
