# Generated by Django 5.2.4 on 2025-08-09 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('number', models.IntegerField(default=1)),
                ('red_corner_damage_dealt', models.IntegerField(default=0)),
                ('blue_corner_damage_dealt', models.IntegerField(default=0)),
                ('red_corner_rank_points_earned', models.IntegerField(default=0)),
                ('blue_corner_rank_points_earned', models.IntegerField(default=0)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', related_query_name='round', to='app_fight.fight')),
            ],
            options={
                'verbose_name': 'Fight Round',
                'verbose_name_plural': 'Fight Rounds',
                'db_table': 'fight_round',
            },
        ),
    ]
