# Generated by Django 4.0.4 on 2022-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('integer', models.IntegerField()),
                ('decimal', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
