# Generated by Django 5.2.4 on 2025-08-09 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability', '0001_initial'),
        ('gorilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('training_type', models.CharField(default='', max_length=100)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('intensity_level', models.IntegerField(default=1)),
                ('capability_gain', models.IntegerField(default=0)),
                ('training_date', models.DateField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='capability.capability')),
                ('gorilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='gorilla.gorilla')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'db_table': 'app_training',
            },
        ),
    ]
