name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development_requirements.txt
          pip install -r mkdocs_requirements.txt

      - name: Package Tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python example/manage.py test --settings=system.settings --noinput

      - name: Documentation Tests
        run: |
          mkdocs build --strict
