name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install Dependencies
        run: uv sync --extra development --extra documentation

      - name: Install Playwright Dependencies
        run: uv run python playwright install --with-deps

      - name: Package Tests
        run: uv run python test_project/manage.py test --settings=system.settings --noinput

      - name: Documentation Tests
        run: uv run mkdocs build --strict
