name: Security Scan

on:
  push:
    paths-ignore:
      - 'requirements.txt'
      - 'Pipfile.lock'
  pull_request:
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit and print output
        run: bandit -c pyproject.toml -r . --severity-level medium --confidence-level low --format txt | tee bandit_report.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit (Dependency Security Check)
        run: pip-audit | tee pip_audit_report.txt

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/trivy

      - name: Run Trivy (Dependency Security Scan)
        run: trivy fs . --severity LOW,MEDIUM,HIGH,CRITICAL --format table | tee trivy_report.txt

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit_report.txt
            pip_audit_report.txt
            trivy_report.txt
          retention-days: 7
