name: Security Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        run: uv python install 3.11

      - name: Install project dependencies
        run: uv sync

      - name: Install security tools
        run: |
          uv tool install pip-audit

      - name: Run pip-audit
        run: uv tool run pip-audit | tee pip_audit_report.txt

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/trivy

      - name: Run Trivy
        run: trivy fs . --severity LOW,MEDIUM,HIGH,CRITICAL --format table | tee trivy_report.txt

      - name: Install TruffleHog 3
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh \
          | sudo sh -s -- -b /usr/local/bin

      - name: Run TruffleHog
        run: trufflehog filesystem . --json --no-update | tee trufflehog_report.txt

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            pip_audit_report.txt
            trivy_report.txt
            trufflehog_report.txt
          retention-days: 7
